root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web/main.go"
  bin = "./tmp/main"
  full_bin = "APP_ENV=dev ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000 # ms

[log]
  level = "debug"

[misc]
  # Hapus file binary lama saat restart
  clean_on_exit = true
